# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('adaptive-load', [
        'core', 
        'internet', 
        'point-to-point', 
        'applications', 
        'flow-monitor'
    ])
    
    if bld.env.ENABLE_EXAMPLES:
        obj = bld.create_ns3_program('adaptive-lb-routing-example', 
            ['adaptive-load', 'internet', 'point-to-point', 'applications', 'flow-monitor'])
        obj.source = 'examples/adaptive-load/adaptive-lb-routing-example.cc'